### PR TITLE
UIBuilder.as fixes of incorrect build of external elements

### PR DESCRIPTION
**Pull request by cleptoman**

### CODE REVIEW

**Comment by ghost** [comment]
Hi, Aleksey

Thanks for the first ever pull request!
I saw your external data change. Is there a reason for the change?
The old way seems to be working fine in the editor (I never tested in the game but I guess it should work the same way)

**Comment by cleptoman** [comment]
Hi. it create the element twice. builds an element of some linked class and after build not children but again instance of our class with children

**Comment by cleptoman** [comment]
this problem i have in my game, not editor

**Comment by yuhengh** [comment]
I just did a test on the demo project and I can't reproduce your problem.
Basically I add a external element to a layout file with another layout file, 

```
  {
    "cls":"starling.display.Sprite",
    "customParams":{
      "container":1,
      "source":"mail_item"
    },
    "params":{
      "name":"mail_item",
      "x":-2.5,
      "y":-58.5
    }
  }
```

and then I implemented 

```
    public function getExternalData(name:String):Object
    {
        return new EmbeddedLayouts.mail_item().toString();
    }
```

It seems to be working fine. What's in your case?

**Comment by cleptoman** [comment]
look at https://bitbucket.org/cleptoman/starling-builder-test/src my test project
at Label class we can see that problem

**Comment by ghost** [comment]
OK. I think I saw your problem.
You shouldn't set customComponentCls to Label inside test_layout.json. Removing it will fix your issue.
Basically the external element inside the parent is just a container, which contains the root of the external element.

**Comment by cleptoman** [comment]
but it sets automaticaly at the import external component.it means i should remove linkage manualy in the config, isn't it?

**Comment by ghost** [comment]
I don't think it sets automatically at the import. Can you double check that?

**Comment by cleptoman** [comment]
it was checked 2 mins ago. it set "Label"after import . however - import external component creates redundant container. my fix remove it and build exacetaly my external component into my editable (in the game). it is expected behavior i think

**Comment by ghost** [comment]
That's definitely a bug. Thanks for spotting that!
I will fix it by not setting it though.
The reason I am making an extra container is because external element is always read-only.
If I want to change the property (x, y, alph, etc) of the container it won't affect the external element itself. Does it make sense to you?

**Comment by cleptoman** [comment]
but external element is container itself - it has a undeletable root. i expect to see Label as a child of my Window. not a Sprite wich contains my Label

**Comment by cleptoman** [comment]
because I added the Label in the editor

**Comment by ghost** [comment]
Hi, Aleksey

I can totally see your point, having an extra container might not be as straight forward as not having it
You fix adds all the children of the external directly to that container.
The problem I can foresee is your fix is disregarding the root of the external layout.
Let’s say if you changed the alpha of the external layout root then it’s not going to work for the parent layout.
Having an extra container can make a clear boundary between parent layout and external layout.
When you are editing inside the parent layout all the content of the external layout is preserved and remained read-only.
I just made a fix by not copying external root data to the parent layout. That was a editor bug. 
https://github.com/mindjolt/starling-builder-editor/commit/ce8e0e106e6266715a72e570ecfeedcfde335034

I will push a new version soon, it should fix your problem, though, you need to go down 1 level to retrieve the root of the external element.
Thanks for the reporting!

**Comment by cleptoman** [comment]
Hi. As i said i did that fix priority for using in games as a library, not for editor compatibility

**Comment by cleptoman** [comment]
il be waiting a new version. thx for your work

**Comment by ghost** [comment]
New version 0.5.5 is out. It should fix your problem. However the auto update doesn't seem to work for the old version. Please download the file from the README.md link and reinstall.

**Pull request closed without merging**
